<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SaeParTunnel.iOS.Extension</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <IsAppExtension>true</IsAppExtension>
    <ApplicationId>com.saepar.tunnel.packet-tunnel</ApplicationId>
    <ApplicationDisplayVersion>2.0.29</ApplicationDisplayVersion>
    <ApplicationVersion>49</ApplicationVersion>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodesignKey Condition="'$(IosSigningKey)' != ''">$(IosSigningKey)</CodesignKey>
    <CodesignKeychain Condition="'$(IosSigningKeychain)' != ''">$(IosSigningKeychain)</CodesignKeychain>
    <CodesignProvision Condition="'$(IosExtensionProvisioningProfile)' != ''">$(IosExtensionProvisioningProfile)</CodesignProvision>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaeParTunnel.Core\SaeParTunnel.Core.csproj" />
    <ProjectReference Include="..\SaeParTunnel.iOSBinding\SaeParTunnel.iOSBinding.csproj" />
  </ItemGroup>
</Project>
